name = "Disastrous Demonstration"
author = "ass tear a hole"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49ebff9bfbbcadf5d5aeecaadfd24784efdd6bcc5f36ca1787eef202dc139bee"

[versions]
forge = "40.2.31"
minecraft = "1.18.2"
